### ISSUE TITLE
Android shows permission on intial load

### ISSUE THREAD

**Issue by Ahmedhamed77** [wn-na/react-native-capture-protection#48]
thank you for the package
but in the latest build, I found that the package on Android asks for permissions once the app loads 
in a real-world app we can't do that we can't ask users to permit photos and videos without telling them what exactly they are going to permit. 

as you can see here once the app opens the permission just pop up and asks the user to give permission 
is there a workaround for that?
Thank you

![photo_2024-08-29_14-45-24](https://github.com/user-attachments/assets/dea99470-49c1-49ce-9d71-5950f7762796)

**Comment by wn-na** [comment]
@Ahmedhamed77 hello

In Android 13 and earlier, to detect a capture event, it detects that a capture image file is created.
To do this, it will ask for that permission.

In our example app, we require this permission to use the `CaptureProtectionProvider`.

**Comment by Ahmedhamed77** [comment]
@wn-na thank you for your response 
the problem is that on the first screen of the app, it always asks permission, so maybe we could have a workaround, just ask permission on the screen where we know that screenshot will be taken, there are some ways to detect screenshots so we could only ask permission on that case ? is that possible?

**Comment by wn-na** [comment]
@Ahmedhamed77 hello

I think it would be a good idea to ask for permission when calling prevent. 

Even if you don't have that permission, you can still prevent screenshots, you just won't be able to detect the event that the screenshot was taken, so I don't think it's necessary to ask for the permission.

I'll give it some more thought and see how i can improve it.

**Comment by wn-na** [comment]
@Ahmedhamed77 hello
I've been thinking about it and would like to make the following changes first.

`CaptureProtectionProvider` no longer asks for permissions as soon as it starts.

When running `preventScreenshot`, `preventScreenRecord`, it will ask for permission.

If you have any better ideas, please let me know!

**Comment by Ahmedhamed77** [comment]
@wn-na I think this is the best approach, I will be waiting
thank you

**Comment by wn-na** [comment]
@Ahmedhamed77 hi
We've deployed to version 1.9.12, would you like to check it out?

**Comment by Ahmedhamed77** [comment]
@wn-na 
it's working now only the capture protection is called, that's nice 
even though I would say it's not user-friendly
for example, I have a screen where I only have text and I try to prevent screenshots there, once the user enters the screen there is a popup of permission where they need to allow photos and videos permission, even if there is nothing related to that. so as I user, I would say that's a spam, what do you think ?

**Comment by wn-na** [comment]
@Ahmedhamed77 When asking for media permissions in a text-only app, it can feel like spam, but before Android 14, there was no way to detect screenshots other than that method, so it's unavoidable. 
It could be improved by not asking for those permissions and only preventing screenshots.

i'm sure with a little more thought, i can come up with a good way to do it, but it's hard right now.
