### ISSUE TITLE
iOS 18 support

### ISSUE THREAD

**Issue by elsa17z** [wn-na/react-native-capture-protection#52]
Thank you for this amazing library! The iOS screen recording detection, isCaptured is deprecated from iOS 18 onwards, and has been replaced by sceneCaptureState https://developer.apple.com/documentation/uikit/uitraitcollection/4292628-scenecapturestate?language=objc, would it be possible to implement this so screen recording detection on iOS can support iOS 18 and above? Thanks!

**Comment by wn-na** [comment]
@elsa17z hi, Thanks for letting i know! i'll add it as soon

**Comment by wn-na** [comment]
@elsa17z  Hi, I've checked, but I'm trying to convert it to a swift over that value and use that function to fix it.
For now, the function I'm using is still working on iOS 18, so can you be patient?

https://developer.apple.com/documentation/swiftui/environmentvalues/isscenecaptured

**Comment by wn-na** [comment]
@elsa17z Thank you for your response. I'm working as quickly and carefully as possible and hope to have some good news for you soon.
