### ISSUE TITLE
TODO: Support New Architecture

### ISSUE THREAD

**Issue by wn-na** [wn-na/react-native-capture-protection#53]

**Comment by Ahmedhamed77** [comment]
@wn-na can I work on this or are you already doing it?

**Comment by wn-na** [comment]
@Ahmedhamed77 nope, unfortunately, i cant work for it...

**Comment by wn-na** [comment]
hi @Ahmedhamed77 

I've checked into that, and there doesn't seem to be any issues with the new architecture as it stands.

For that reason, i'm not working on it right now, and it will be fixed when i work on migrating to swift and kotlin

**Comment by nalladev** [comment]
![Image](https://github.com/user-attachments/assets/9fd77a3a-b8a5-4d91-a3e1-3418263bf882)

If it support's new architecture shouldn't we update it here. 
https://reactnative.directory

**Comment by wn-na** [comment]
@nalladev Thanks for letting me know! I'll update this soon!
