### ISSUE TITLE
Prevent Screenshot is not working in android

### ISSUE THREAD

**Issue by ricophie03** [wn-na/react-native-capture-protection#54]
Hi, I'm tried to prevent any screenshot or screen recording on specific screen in my app. I tried to add an effect like your documentation here:
`React.useEffect(() => {
    bindProtection();
    return () => {
      releaseProtection(true);
    };
  }, []);`

I tried it in ios simulator and the screenshot is expected to be black screen only. But in android, both my real device and emulator, I'm still able to screenshot while the screenrecord is stop automatically ( i expected the result of the record would be black screen only). 

My Android device :  `Android 11`
My Android emulator device :` Android 13`
react-native :` 0.72.7`
react-native-capture-protection: `1.9.12`

**Comment by wn-na** [comment]
hi @ricophie03. `bindProtection` is must be used with `CaptureProtectionProvider`.  can you use it?
or try `preventScreenshot` function?
