### ISSUE TITLE
Cannot build iOS due to `Use of undeclared identifier 'facebook'`

### ISSUE THREAD

**Issue by zaiehilmi** [wn-na/react-native-capture-protection#57]
Hi there,

React native: 0.76.2
Xcode: 16.1
react-native-capture-protection: 1.9.13

I got this error after I try to build for iOS. after looking into the xcode, from this code got error as the title.

here is the path where you can find the issue `node_modules/react-native-capture-protection/ios/CaptureProtection.mm`

```
#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeCaptureProtectionSpecJSI>(params);
}
#endif
```

I commented it and after that I can successfully build.

**Comment by wn-na** [comment]
hello. @zaiehilmi 

I haven't tested against RN 0.76, so I haven't found that issue.

The logic looks good without that part. I'll delete it and deploy it! Thank you!
